--!strict

export type AttributesState = {
	Damage: number,
	MaxHP: number,
	Regen: number,
	Range: number,
	Reflect: number,
	LaunchSpeed: number,
	ChargeSpeed: number,
	MoveSpeed: number,
}

export type PlayerState = {
	UserId: number,
	MapName: string,
	ArenaStatus: string,
	TeamId: string,
	Level: number,
	Exp: number,
	Size: number,
	MaxHP: number,
	CurrentHP: number,
	BaseDamage: number,
	RegenRate: number,
	ReflectDamage: number,
	LaunchSpeed: number,
	LaunchRange: number,
	ChargeSpeed: number,
	MoveSpeed: number,
	DamageMultiplier: number,
	HPBonus: number,
	LaunchSpeedBonus: number,
	RegenBonus: number,
	KnockbackResistance: number,
	SlingshotType: string,
	ChargeValue: number,
	CurrentVelocity: Vector3,
	InvulnerableUntil: number,
	LastDamageTime: number,
	InvulCooldownUntil: number,
	Diamonds: number,
	HpPotions: number,
	NextHpPotionUseTime: number,
	RespawnCountThisMatch: number,
	AttributePoints: number,
	DamageDealt: number,
	IsTeleporting: boolean,
	CooldownEndTime: number,
	LastReleaseDuration: number,
	Attributes: AttributesState,
	IsAlive: boolean,
	IsCharging: boolean,
	MovementState: string,
	IsVisible: boolean,
	StunnedUntil: number,
	ScaleMultiplier: number,
	BonusMaxHP: number,
	BonusDamageMultiplier: number,
	LevelDamageBonus: number,
}

return {}
