--!strict

export type AttributesState = {
	Damage: number,
	MaxHP: number,
	Regen: number,
	Range: number,
	Reflect: number,
	LaunchSpeed: number,
	ChargeSpeed: number,
	MoveSpeed: number,
}

export type OwnedLauncher = {
	definitionId: string,
	star: number,
	level: number,
	acquiredAt: number,
}

export type PlayerState = {
	UserId: number,
	CurrentMap: string?,
	LocationState: string,
	TeamId: string?,
	Level: number,
	Exp: number,
	Size: number,
	MaxHP: number,
	CurrentHP: number,
	BaseDamage: number,
	RegenRate: number,
	ReflectDamage: number,
	LaunchSpeed: number,
	LaunchRange: number,
	ChargeSpeed: number,
	MoveSpeed: number,
	DamageMultiplier: number,
	HPBonus: number,
	LaunchSpeedBonus: number,
	RegenBonus: number,
	KnockbackResistance: number,
	LaunchershotType: string,
	EquippedLauncherInstanceId: string?,
	OwnedLaunchers: { [string]: OwnedLauncher }?,
	ChargeValue: number,
	CurrentVelocity: Vector3,
	InvulnerableUntil: number,
	LastDamageTime: number,
	InvulCooldownUntil: number,
	Diamonds: number,
	HpPotions: number,
	NextHpPotionUseTime: number,
	RespawnCountThisMatch: number,
	DeathCountThisMatch: number,
	SelectedPlayerMode: string,
	ActivePlayerMode: string,
	ForcedHuman: boolean,
	FinalPhaseDeathConverted: boolean,
	AttributePoints: number,
	DamageDealt: number,
	IsTeleporting: boolean,
	CooldownEndTime: number,
	LastReleaseDuration: number,
	Attributes: AttributesState,
	IsAlive: boolean,
	IsCharging: boolean,
	MovementState: string,
	IsVisible: boolean,
	StunnedUntil: number,
	ScaleMultiplier: number,
	BonusMaxHP: number,
	BonusDamageMultiplier: number,
	LevelDamageBonus: number,
	ActiveFlags: any?,
	Armor: number?,
	ExpBonus: number?,
	RankPoints: number?,
}

return {}
