--!strict

local BalanceConfig = {
	CollisionCooldown = 0.3,
	MaxDamagePerHit = 350,
	MinVelocityToCollide = 8,
	VelocityDecayFactor = 0.6,
	VelocityStopThreshold = 5,
	MaxVelocity = 170,
	BaseImpactForce = 60,
	SpeedDamageFactor = 0.065,
	SizeDamageFactor = 0.75,
	ChargeDamageFactor = 0.8,
	KnockbackFactor = 0.35,
	MaxChargeSelfDamage = 18,
	MaxKnockback = 180,
	SelfDamageRatio = 0.5,
	MaxSelfDamageToCurrentHpRatio = 1.5,
	DamageLevelBonusMin = 2,
	DamageLevelBonusMax = 10,
	DamageLevelBonusCap = 1000,
	ReflectDamageCap = 0.15,
	MaxDamageBonusFromAttributes = 0.25,
	MaxHpBonusFromAttributes = 0.30,
	AttributeCapPerStat = 20,
	DefaultInvulnerableSeconds = 1.0,
	HitInvulSeconds = 0.25,
	DefaultWalkSpeed = 16,
	BaseSize = 1,
	LevelGrowthMultiplier = 0.08,
	BaseHP = 100,
	BaseDamage = 20,
	BaseExp = 100,
	ExpExponent = 1.3,
	SizeSqrtMultiplier = 0.08,
	PostLevel30SizeScalar = 0.3,
	KillExp = 120,
	DamageToExpRatio = 0.45,
	FoodExp = 25,
	FoodHealth = 8,
	FoodSpawnCountPerMap = 8,
	FoodGridCellSize = 24,
	FoodRespawnDelay = 1.5,
	CorridorSizeLimit = 8,
	AntiGiantSizeLimit = 12,
	RespawnDiamondCosts = { 10, 15, 20 },
	RespawnRetainSizePaid = 0.7,
	RespawnRetainLevelPaid = 0.7,
	RespawnRetainLevelFree = 0.3,
	PassiveHealPercent = 0.02,
	PassiveHealDelay = 1.0,
	PassiveHealMovementThreshold = 2,
	MatchBuffCost = 20,
	MatchBuffMaxBoost = 0.10,
	DiamondsPerPrestigeLevelDivisor = 5,
}

return BalanceConfig
